frontend:
  enabled: true
  # 配置为ui的svc的名称与端口
  extSvcName: shenyu-admin
  extSvcPort: 9095
  # 访问ks的域名, e.g. www.ks.com,192.168.50.208.nip.io
  domain: localhost
  # 挂载位置 e.g. topbar,global,toolbox,access,cluster,workspace,project,platformSettings
  extParent: topbar
  # ui的超链接名称
  extTitle: ShenYu 网关
  # 扩展包描述
  extDesc: "shenyu admin"
  # ingress controller 对外服务的Node端口
  ingressPort: 30888
  
shenyu:
  admin:
    enabled: true
    # replicas of admin, K8s will load balance the requests
    replicas: 1
    service:
      port: 9095
      targetPod: 9095
      # if you want to change "admin service port", please edit here
      nodePort: 30095
  bootstrap:
    enabled: true
    # replicas of bootstrap, K8s will load balance the requests
    replicas: 2
    service:
      port: 9195
      targetPod: 9195
      # if you want to change "bootstrap service port", please edit here
      nodePort: 30195

  dataSource:
    # options: [h2, mysql, pg, oracle]
    active: h2
    # init database and tables
    initEnabled: true
    h2:
      # use custom datasource url, default is jdbc:h2:mem:~/shenyu;DB_CLOSE_DELAY=-1;MODE=MySQL;
      url: ""
      username: sa
      password: sa
    mysql:
      # use custom datasource url and ignore other configs, the format is jdbc:mysql://xxxxxxx
      urlOverride: ""
      ip:
      port: 3306
      username: root
      password:
      database: shenyu
      # mysql driver class name
      # mysql5   : com.mysql.jdbc.Driver
      # mysql6-8 : com.mysql.cj.jdbc.Driver
      driverClass: com.mysql.cj.jdbc.Driver
      connectorVersion: 8.0.23
    pg:
      # use custom datasource url and ignore other configs, the format is jdbc:postgresql://xxxxxxx
      urlOverride: ""
      ip:
      port: 5432
      username: postgres
      password:
      database: shenyu
      # pg driver class name
      driverClass: org.postgresql.Driver
      connectorVersion: 42.5.0
    oracle:
      # use custom datasource url and ignore other configs, the format is jdbc:oracle:xxxxxx
      urlOverride: ""
      ip:
      port: 1521
      username: root
      password:
      serviceName: shenyu
      # oracle driver class name
      driverClass: oracle.jdbc.OracleDriver
      connectorVersion: 19.3.0.0
