apiVersion: extensions.kubesphere.io/v1alpha1
kind: JSBundle
metadata:
  name: {{ include "frontend.fullname" . }}-js-bundle
spec:
  rawFrom:
    rawFrom:
    configMapKeyRef:
      key: index.js
      name: {{ include "frontend.fullname" . }}-ks-frontend
      namespace: {{ .Release.Namespace }}
status:
  state: Available
  link: /dist/{{ include "frontend.fullname" . }}/index.js

