apiVersion: extensions.kubesphere.io/v1alpha1
kind: JSBundle
metadata:
  name: shenyu-js
spec:
  rawFrom:
    configMapKeyRef:
      key: index.js
      name: shenyu-cm
      namespace: {{ .Release.Namespace }}
status:
  link: /dist/shenyu/index.js
  state: Available