{{- if .Values.admin.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ .Release.Namespace }}
  name: shenyu-admin
  labels:
    {{- include "shenyu.admin.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shenyu-admin
  minReplicas: {{ .Values.admin.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.admin.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.admin.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.admin.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.admin.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.admin.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
